# Generated by Django 4.1.7 on 2023-03-06 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertise_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertise_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.advertise')),
            ],
        ),
        migrations.CreateModel(
            name='employee_Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_experience', models.IntegerField(default=0)),
                ('employee_graduation_year', models.IntegerField()),
                ('employee_track', models.CharField(max_length=100)),
                ('employee_description', models.TextField()),
                ('employee_projects', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.employee_cv')),
            ],
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
