# Generated by Django 4.1.7 on 2023-03-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_advertise_company_employee_cv_employees_delete_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_cv',
            name='employee_projects',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
