# Generated by Django 4.1.7 on 2023-03-06 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_employee_cv_employee_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_cv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CV', to='pages.employee_cv'),
        ),
    ]
