# Generated by Django 4.1.7 on 2023-03-06 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_employees_employee_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='advertise_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_cv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.employee_cv'),
        ),
    ]
