# Generated by Django 4.1.7 on 2023-03-21 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_activites_hoppies_remove_company_advertise_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoppies',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pages.activites'),
            preserve_default=False,
        ),
    ]
