# Generated by Django 4.1.7 on 2023-03-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_hoppies_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoppies',
            name='hoppy_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hoppies',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
