# Generated by Django 4.1.7 on 2023-04-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_book_video_remove_hoppies_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(upload_to=''),
        ),
    ]
