# Generated by Django 4.1.7 on 2023-04-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_book_url_alter_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoppies',
            name='image',
        ),
        migrations.AddField(
            model_name='hoppies',
            name='url',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
